

CREATE TABLE PARCHES_SQL
(
    NOMBRE character varying(10),
    CONSTRAINT pk_parches_sql PRIMARY KEY(nombre)
);

CREATE TABLE CONFIG_ITERACION
(
	ITERACION_ID            NUMBER(19) NOT NULL,
	PORCENTAJE_ACEPTACION_MATCH  NUMBER(19,4) NOT NULL,
        APLICA_PALABRAS_OMITIDAS NUMBER(1) NOT NULL
)
;

CREATE TABLE ESTADO
(
	ID_ESTADO  NUMBER(10) NOT NULL,
	NOMBRE     VARCHAR(255) NOT NULL
)
;

CREATE TABLE ITERACION
(
	ID_ITERACION                NUMBER(19) NOT NULL,
	PROCESO_ID                  NUMBER(19) NOT NULL,
	NUM_ITERACION               NUMBER(10) NOT NULL,
	ESTADO_ID                   NUMBER(10),
	NUM_MATCH                   NUMBER(10),
	NUM_NO_MATCH                NUMBER(10),
        RUTA_ARCHIVO_ORIGINAL       VARCHAR(2000),
	RUTA_ARCHIVO_MATCH          VARCHAR(2000),
	RUTA_ARCHIVO_NO_MATCH       VARCHAR(2000),
	RUTA_ARCHIVO_FALLA_CRITICA  VARCHAR(2000),
        FECHA_EN_COLA               DATE,
	FECHA_INICIO                DATE,
	FECHA_FIN                   DATE
)
;

CREATE TABLE PERFIL
(
	ID_PERFIL  NUMBER(10) NOT NULL,
	NOMBRE     VARCHAR(255) NOT NULL
)
;

CREATE TABLE PROCESO
(
	ID_PROCESO              NUMBER(19) NOT NULL,
	NOMBRE                  VARCHAR(255),
	FECHA_CREACION          DATE,
	FECHA_ULTIMA_EJECUCION  DATE,
	ESTADO_ID               NUMBER(10),
	TOTAL_MATCH             NUMBER(10),
	TOTAL_NO_MATCH          NUMBER(10),
        RUTA_ARCHIVO_PALABRAS_OMITIDAS  VARCHAR(2000)
)
;

CREATE TABLE USUARIO
(
	RUT         NUMBER(10) NOT NULL,
	PERFIL_ID   NUMBER(10),
	NOMBRES     VARCHAR(255) NOT NULL,
	AP_PATERNO  VARCHAR(255) NOT NULL,
	AP_MATERNO  VARCHAR(255) NOT NULL,
	EMAIL       VARCHAR(255) NOT NULL,
	PASSWORD    VARCHAR(1000) NOT NULL,
	HABILITADO  NUMBER(1) NOT NULL
)
;

ALTER TABLE CONFIG_ITERACION ADD CONSTRAINT PK_CONFIG_ITERACION
	PRIMARY KEY (ITERACION_ID)
;

ALTER TABLE ESTADO ADD CONSTRAINT PK_ESTADO
	PRIMARY KEY (ID_ESTADO)
;

ALTER TABLE ITERACION ADD CONSTRAINT PK_ITERACION
	PRIMARY KEY (ID_ITERACION)
;

ALTER TABLE PERFIL ADD CONSTRAINT PK_PERFIL
	PRIMARY KEY (ID_PERFIL)
;

ALTER TABLE PROCESO ADD CONSTRAINT PK_PROCESO
	PRIMARY KEY (ID_PROCESO)
;

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO
	PRIMARY KEY (RUT)
;

ALTER TABLE CONFIG_ITERACION ADD CONSTRAINT FK_CONFIG_ITERACION_ITERACION
	FOREIGN KEY (ITERACION_ID) REFERENCES ITERACION (ID_ITERACION)
;

ALTER TABLE ITERACION ADD CONSTRAINT FK_ITERACION_ESTADO
	FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO (ID_ESTADO)
;

ALTER TABLE ITERACION ADD CONSTRAINT FK_ITERACION_PROCESO
	FOREIGN KEY (PROCESO_ID) REFERENCES PROCESO (ID_PROCESO)
;

ALTER TABLE PROCESO ADD CONSTRAINT FK_PROCESO_ESTADO
	FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO (ID_ESTADO)
;

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_PERFIL
	FOREIGN KEY (PERFIL_ID) REFERENCES PERFIL (ID_PERFIL)
;

CREATE SEQUENCE SEQ_ITERACION_ID_ITERACION
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    MINVALUE 1
	NOCYCLE
	NOCACHE
	NOORDER
;

CREATE SEQUENCE SEQ_PROCESO_ID_PROCESO
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    MINVALUE 1
	NOCYCLE
	NOCACHE
	NOORDER
;

INSERT INTO PARCHES_SQL (NOMBRE) VALUES ('000.sql');

